// See https://aka.ms/new-console-template for more information
// <auto-generated/>
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace MyNamespace
{
    class Program
    {
        static void Main(String[] args)
        {
            Console.WriteLine("Enter a number for giving number of ones:");
            Console.WriteLine(BestKata.CountBits(Convert.ToInt32(Console.ReadLine())));

        }
    }
    public class Kata
    {
        public static int CountBits(int n)
        {
            int ones = 0;
            int i;
            while(n > 0)
            {
                i = n % 2;
                n = n/2;
                _= (i == 1)? ones++ : i;
            }
            return ones;
        }
    }

    public class BestKata
    {
        public static int CountBits(int n)
        {
            return Convert.ToString(n, 2).Count(x => x == '1');
        }
    }


}
